### ISSUE TITLE
I want RTP to RTMP

### ISSUE THREAD

**Issue by hicodeboy** [Kurento/mediasoup-demos#1]
I want to RTP to RTMP ,
please tell me ,I want to do .thanks.
I english is poor.

**Comment by j1elo** [comment]
Use the [Kurento group](https://groups.google.com/forum/#!forum/kurento) for questions about Kurento Media Server.

At this moment Kurento does not support RTMP. It only supports WebRTC and RTP. You need an external server or a custom application written with GStreamer.
